import Head from "next/head";

export default function Meta() {
  return (
    <Head>
      <title>Recipes</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
}
